FROM public.ecr.aws/lambda/python:3.12

# Install build tools
RUN dnf install -y zip unzip bc && \
    pip install --upgrade pip && \
    pip install poetry poetry-plugin-export pip-audit

WORKDIR /build

COPY build-lambda.sh /build/
RUN chmod +x /build/build-lambda.sh

ENTRYPOINT ["/build/build-lambda.sh"]
